# Permalinks
permalink:           pretty

# Setup
title:               Kapil Kumawat
tagline:             Data and stuff
introurl:            /about
intro:               About
url:                 http://kapilkumawat.com
paginate:            1
baseurl:             ""
analytics_id:        UA-84727575-1
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kapil Kumawat
  url:               https://twitter.com/kapilkumawat
  email:             kwtkapil@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://kapilkumawat.github.com/blog

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
